language: node_js

install: npm install

cache:
  directories:
    - "node_modules"

script: npm start

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
